name: IaC Security Scanning

on:
    pull_request:
        branches:
            - dev
        paths:
            - '*/*.tf'

permissions:
  contents: read
  security-events: write

jobs:

  infrastructure-security:
    name: Infrastructure Security
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec (Infrastructure Security)
        if: always() 
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Run Checkov (Policy Compliance)
        uses: bridgecrewio/checkov-action@v12
        if: always() 
        with:
          framework: terraform

      - name: Upload tfsec Results
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: infrastructure-security-tfsec

      - name: Upload Security Results
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: infrastructure-security-checkov